spring:
   profiles:
        active:
        -dev
---
spring:
   profiles: dev
   application:
        name: microservicecloud-config-zzm-dev
---
spring
   profiles: test
   application:
        name: microservicecloud-config-zzm-test
# 请保存为UTF-8格式
